services:
  - type: web
    name: tandau-web-messenger
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_messenger.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
